import streamlit as st
from langchain_groq import ChatGroq
import smtplib
from email.message import EmailMessage
import re
from dotenv import load_dotenv
from PyPDF2 import PdfReader
import os
# ---------------------------
# Load ENV
# ---------------------------
load_dotenv()

# ---------------------------
# Initialize LLM
# ---------------------------
api_key = os.getenv("GROQ_API_KEY") or st.secrets["GROQ_API_KEY"]
sender_email = os.getenv("EMAIL_USER") or st.secrets["EMAIL_USER"]
sender_password = os.getenv("EMAIL_PASS") or st.secrets["EMAIL_PASS"]

llm = ChatGroq(
    model="qwen/qwen3-32b",
    temperature=0,
    api_key=api_key,
)

# ---------------------------
# Helpers
# ---------------------------

def valid_email(email):
    pattern = r"^[\w\.-]+@[\w\.-]+\.\w+$"
    return re.match(pattern, email)


def extract_pdf_text(file):
    text = ""
    try:
        reader = PdfReader(file)
        for page in reader.pages:
            text += page.extract_text() or ""
    except:
        pass
    return text


def send_email(sender_email, sender_password, recipient, subject, body, attachment=None):

    msg = EmailMessage()
    msg["From"] = sender_email
    msg["To"] = recipient
    msg["Subject"] = subject
    msg.set_content(body)

    # 📎 Attach only attachment PDF (NOT context PDF)
    if attachment is not None:
        file_data = attachment.getvalue()
        file_name = attachment.name

        msg.add_attachment(
            file_data,
            maintype="application",
            subtype="pdf",
            filename=file_name
        )

    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as smtp:
            smtp.login(sender_email, sender_password)
            smtp.send_message(msg)

        return "✅ Email sent successfully!"

    except smtplib.SMTPAuthenticationError:
        return "❌ Authentication failed."

    except Exception as e:
        return f"❌ Failed: {str(e)}"


# ---------------------------
# UI
# ---------------------------

st.set_page_config(page_title="MailGPT - AI Email Agent", page_icon="📧")

st.title("📧 MailGPT - Your AI Email Assistant")

st.info("""
🔐 Important: Gmail App Password Required

This app will NOT work with your normal Gmail password.

Google blocks less-secure login attempts, so you must use an App Password.""")



### 📌 What is an App Password?
with st.expander("""It is a **16-digit secure password generated by Google** for apps like this.

### ⚙️ How to Generate App Password"""):
    st.write("""
1. Go to: https://myaccount.google.com/security  
2. Turn ON **2-Step Verification (2FA)**  
3. After enabling 2FA, go to:  
   👉 https://myaccount.google.com/apppasswords  
4. Select:
   - App → **Mail**
   - Device → **Other (Custom name)** → type anything like "Email Agent"
5. Click **Generate**
6. Copy the **16-character password**

---

### ⚠️ Important Notes

- ❌ Do NOT use your normal Gmail password  
- ✅ Paste the 16-digit App Password in the app  
- 🔒 Keep it private (like your real password)

---

💡 Example App Password:
`abcd efgh ijkl mnop`
(Use without spaces)

""")
# ---------------------------
# Form
# ---------------------------

with st.form("email_form"):

    sender_email = st.text_input("Sender Email")
    sender_password = st.text_input("App Password", type="password")
    recipient = st.text_input("Recipient Email")

    purpose = st.text_area("What is the email about?")

    # 📄 Context PDF (for AI only)
    st.markdown("### 📄 Extra Context for AI (Optional)")
    context_pdf = st.file_uploader(
        "Upload PDF (used only for generating better email)",
        type=["pdf"],
        key="context_pdf"
    )

    # 📎 Attachment PDF (for sending)
    st.markdown("### 📎 Attachment (Optional)")
    attachment_pdf = st.file_uploader(
        "Upload PDF to attach with email",
        type=["pdf"],
        key="attachment_pdf"
    )

    submit = st.form_submit_button("Generate Email")


# ---------------------------
# Generate Email
# ---------------------------

if submit:

    if not valid_email(sender_email) or not valid_email(recipient):
        st.error("❌ Invalid email format")

    else:
        pdf_text = ""

        # Only use context PDF for LLM
        if context_pdf:
            pdf_text = extract_pdf_text(context_pdf)

        prompt = f"""
You are an email assistant.

User request:
{purpose}

Extra context:
{pdf_text[:2000]}

You are a professional email assistant.

Write a clear and human sounding email based on the user's request.

Important instructions:
- Do not use any special characters such as dashes, asterisks, emojis, or symbols.
- Do not use bullet points or decorative formatting.
- Write in simple, natural, human language.
- Keep the tone professional, polite, and realistic.
- Avoid robotic or overly formal phrases.
- Do not add unnecessary formatting or spacing.

The email should feel like it was written by a real person.

User request:
{purpose}

Return strictly in this format:

Subject: <subject>

Body:
<body>

"""

        response = llm.invoke(prompt)
        text = response.content

        subject = ""
        body = ""

        if "Subject:" in text and "Body:" in text:
            subject = text.split("Subject:")[1].split("Body:")[0].strip()
            body = text.split("Body:")[1].strip()

        # Save to session
        st.session_state.subject = subject
        st.session_state.body = body
        st.session_state.sender_email = sender_email
        st.session_state.sender_password = sender_password
        st.session_state.recipient = recipient
        st.session_state.attachment = attachment_pdf


# ---------------------------
# Show Output
# ---------------------------

if "subject" in st.session_state:

    st.subheader("📌 Subject")
    st.write(st.session_state.subject)

    st.subheader("📄 Email Body")

    edited_body = st.text_area(
        "Edit Email",
        st.session_state.body,
        height=250
    )

    if st.button("📤 Send Email"):

        result = send_email(
            st.session_state.sender_email,
            st.session_state.sender_password,
            st.session_state.recipient,
            st.session_state.subject,
            edited_body,
            st.session_state.get("attachment")
        )

        st.success(result)